converter:
  source_folder: input/
  languages:
  - tr
  - tur
  - trk
streamer:
  content_folder: streams/
  port_range_start: 1923
  port_range_end: 1924
  protocol: hls
  auto_resume: false
  current_folder: '1207_1907'
  channel_prefix: Salon
  epg_timezone: '+0300'
  playlists:
    '1207_1907':
    - port: 1923
      files: []
    - port: 1924
      files: []
server:
  host: 0.0.0.0
  port: 8080
